### ISSUE TITLE
Support ignoring order of child elements in diffs

### ISSUE THREAD

**Issue by stringbean** [stringbean/scala-xml-compare#2]
We should be able to (optionally) treat this:
```xml
<parent>
    <child1/>
    <child2/>
</parent>
```

as being equal to:
```xml
<parent>
    <child2/>
    <child1/>
</parent>
```

**Comment by metyl** [comment]
Hi @stringbean maybe it should be another matcher called `beSimiarXml` or sth like this.
Any plans to implement this feature?

**Comment by stringbean** [comment]
It's definitely on my TODO list. My initial thought was that it would be part of the `DiffOption`s something like:

```scala
XmlCompare.compare(left, right, Set(DiffOption.IgnoreChildOrder))
```

Having a `beSimilar` shortcut would probably be a good idea though!
