### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by fsanaulla** [stringbean/scala-xml-compare#6]
Hello @stringbean.

Thank you for your library!

There is a readme issue in the quickstart section.
> libraryDependencies += "purpledragon.software.xml" %% "xml-compare" % "<version>"

it should be:

`libraryDependencies += "software.purpledragon.xml" %% "xml-compare" % "<version>"`

Also will be great to add information about `XmlMatchers` for scalatest/specs2 modules.

Thank you!

**Comment by stringbean** [comment]
This is now sorted and there’s a docs site with details.
